/* Not well-typed yet; can be updated later */

export interface MastodonAPIError {
  error: string,
}

export interface MastodonAPIResponseStatus {
  id: string,
  created_at: string,
  in_reply_to_id: string | null,
  in_reply_to_account_id: string | null,
  sensitive: boolean,
  spoiler_text: string,
  visibility: "public" | "unlisted" | "private" | "direct",
  language: string,
  uri: string,
  url: string,
  replies_count: number,
  reblogs_count: number,
  favourites_count: number,
  edited_at: string | null,
  favourited: boolean,
  reblogged: boolean,
  muted: boolean,
  bookmarked: boolean,
  pinned: boolean,
  content: string,
  filtered: Array<unknown>,
  reblog: boolean,
  application: {
    name: string,
    website: string,
  },
  account: {
    id: string,
    username: string,
    acct: string,
    display_name: string,
    locked: boolean,
    bot: boolean,
    discoverable: boolean,
    group: boolean,
    created_at: string,
    note: string,
    url: string,
    avatar: string,
    avatar_static: string,
    header: string,
    header_static: string,
    followers_count: number,
    following_count: number,
    statuses_count: number,
    last_status_at: string,
    noindex: boolean,
    emojis: Array<object>,
    fields: Array<object>,
  },
  media_attachments: Array<unknown>,
  mentions: Array<unknown>,
  tags: Array<unknown>,
  emojis: Array<unknown>,
  card: unknown | null,
  poll: unknown | null,
}
